n = str(input('Digite um nome: ')).upper().strip()
print('Analisando seu nome...')
nome = n.split()
print('Seu primeiro nome é {}'.format(nome[0]))
print('Seu ultimo nome nome é {}'.format(nome[len(nome)-1]))
